[project]
name = "decentralized-mint-backend"
authors = ["Blockchain Innovation Team"]
description = "A decentralized backend for digital asset minting and management"
telemetry = false
requirements = []
[contracts.digital-asset-mint]
path = "contracts/digital-asset-mint.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
